# Generated by Django 3.2.15 on 2022-09-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanksBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20, verbose_name='Название банка')),
                ('term_min', models.IntegerField(max_length=3, verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.IntegerField(max_length=3, verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.IntegerField(max_length=3, verbose_name='Ставка, ОТ')),
                ('rate_max', models.IntegerField(max_length=3, verbose_name='Ставка, ДО')),
                ('payment_min', models.IntegerField(max_length=20, verbose_name='Ставка кредита, ОТ')),
                ('payment_max', models.IntegerField(max_length=20, verbose_name='Ставка кредита, ДО')),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_price', models.IntegerField(help_text='Введите стоимость недвижимости в рублях без копеек', max_length=20, verbose_name='Стоимость объекта недвижимости')),
                ('first_pay', models.IntegerField(help_text='Введите первоночальный взнос в рублях без копеек', max_length=20, verbose_name='Первоночальный взнос')),
                ('time_of_pay', models.IntegerField(help_text='Введите срок ипотеки', max_length=3, verbose_name='Срок ипотеки')),
            ],
        ),
    ]
