# Generated by Django 3.2.15 on 2022-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgagecalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banksbase',
            name='rate_max',
            field=models.FloatField(max_length=5, verbose_name='Ставка, ДО'),
        ),
        migrations.AlterField(
            model_name='banksbase',
            name='rate_min',
            field=models.FloatField(max_length=5, verbose_name='Ставка, ОТ'),
        ),
    ]
