# Generated by Django 3.2.15 on 2022-09-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgagecalc', '0002_auto_20220905_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksbase',
            name='payment',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Платеж в месяц'),
        ),
    ]
